### PR TITLE
Two automatic calibrations (native and LSR) on g5 restarts

### PR DESCRIPTION
**Pull request by efidoman**

### CODE REVIEW

**Comment by efidoman** [comment]
Yes, I didn't notice yesterday that my git push had a typo. Updated now. Still need to add a check for LSR to make sure it has more than 3 entries.

**Comment by efidoman** [comment]
OK - all the changes for the 1st cut should be reflected now.

**Comment by efidoman** [comment]
Should we disable native calibrates LSR for 6 hours post restart? If so, that would be easy to do just by touching the file in the restart section. it would delay the next native calibrates LSR for 6 hours from the restart.

**Comment by scottleibrand** [comment]
Yes, at a minimum. It might also be good to somehow figure out how to use expired readings when available, at least until the first real calibration is entered. But I’m not sure how to do that robustly.

**Comment by tynbendad** [comment]
it seems like you could keep around the 'lsr-calibrates-native-next-cycle' file for N hours, and instead of calibrating lsr from native you could do the reverse while the file exists...  although i worry about code that auto calibrates native, so maybe have a xdripjs.json flag to disable it.

**Comment by scottleibrand** [comment]
That’s in line with what I was thinking originally. But I’m not certain whether that would give better accuracy on a restarted session vs. just calibrating it once or twice a day. Maybe start with just suppressing native-calibrates-LSR behavior for the first day or two before we think about doing any more LSR-calibrates-native than absolutely needed to get the sensor restarted? That at least ensures that the transmitter will read safely low of the restart drift isn’t corrected by real calibrations.

**Comment by efidoman** [comment]
Sounds good. I'll do that. Is there a way to touch a file for a future date/time? If so, then suppressing native-calibrates-lsr for 24 hours is easy - one line.

**Comment by efidoman** [comment]
Can you both take another look? I added the touch to disable native-calibrates-lsr for 24 hours. 

Also, are either of you able to test the auto restart on a non-new firmware transmitter?

Also, I updated cgm-stop to not time travel if new firmware automatically. It still automatically time travels back 2 hours for g5 and g6 old firmware.

**Comment by efidoman** [comment]
Good question. The touch -d uses a negative 24 hours ago so that actually touches the file with a date/time that is 24 hours in the future. However, you raise a good point. It should actually be "-18 hour ago" in order to delay native-calibrates-lsr for 24 hours. I'll make that change now.

**Comment by tynbendad** [comment]
awesome, i didn't know you could use a negative there.

**Comment by scottleibrand** [comment]
Sorry, I didn't get around to testing this before our G5 transmitter died. We're back to G4 for now and will need to get another one (rebatteried maybe) before I can test further.

**Comment by tynbendad** [comment]
re-battery one Scott, its really easier to do than you might think.

**Comment by scottleibrand** [comment]
Where are the best instructions? Do they detail what equipment is required?

**Comment by tynbendad** [comment]
This is the video I used, but it looks like Katie has a video on YouTube for g5 also. 
https://m.youtube.com/watch?v=OOPZI2tas50

**Comment by scottleibrand** [comment]
Thanks. That's a lot of equipment (drills, etc.) I don't have, so I think we'll get one from someone who has the necessary kit and knows how to do it.

**Comment by tynbendad** [comment]
I think I used a Dremel, in case you have that. If you want I can send you my test g5 tx, it has a lid so you can swap batteries easily, not sure it's good for real use that way. I don't use it anymore, need to figure out g6 battery replacements someday. Pm me if you want it.

**Pull request merged**
