### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by daviddrozh**

### CODE REVIEW

**Comment by efidoman** [comment]
Thanks for the PR. Can you remind me why we want to remove the node upgrade and npm install from Logger's global-install?

**Comment by daviddrozh** [comment]
This was a workaround I was working on for my personal rig.
I’m running Jubilinux 0.2.0. 
I was unable to upgrade Nodejs and NPM through the instructions because Jessie-updates and Jessie-backports repositories have both been taken down.
I was attempting to upgrade them via nvm, and install logger though the modified code (current release of Logger does not recognize that npm is installed when installing through nvm)
That workaround failed.
I did end up updating nodejs by changing the repositories in sources.list, but with yesterday’s release of OpenAPS 0.6.3, I’d assume that this (along with upgrading to jubilinux 0.3.0) will resolve all the issues I was having.

**Comment by efidoman** [comment]
OK - I will try to test out a new install on my backup rig this week.

**Comment by daviddrozh** [comment]
Thanks, really appreciate it. Have been struggling to get Logger to work with G6.

**Pull request closed without merging**
